name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract
        run: Expand-Archive ngrok.zip

      - name: Auth
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Install DirectX
        run: choco install directx -y

      - name: Enable gaming services
        run: sc config xgpsvc start=auto
        run: sc start xgpsvc

      - name: Set Remote Desktop connection speed to "Performance"
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "ConnectionType" -Value 0

      - name: Add runneradmin user to Remote Desktop Users group
        run: net localgroup "Remote Desktop Users" "runneradmin" /add

      - name: Create Tunnel
        run: .\ngrok\ngrok.exe tcp 3389
        
